ref(*): refactor to act as jnlp-slave
deis/jenkins-node pull request #9
Opened 2017-04-05 17:20 UTC by vdice

For use with the Kubernetes Jenkins Plugin.

TODO
 - [ ] add/modify docs
 - [ ] either update chart dir or remove (if chart removed, external ci updates will be needed)

2017-04-05 19:23 UTC, bacongobbler requested changes

2017-04-05 19:23 UTC, bacongobbler commented on Dockerfile
> +ARG VERSION=3.7
can we change this to JENKINS_VERSION for clarity?

2017-04-05 19:23 UTC, bacongobbler commented on Dockerfile
> +COPY rootfs/bin/jenkins-slave /usr/local/bin/jenkins-slave
How about we keep this as `COPY rootfs /` and dump the jenkins-slave script in `rootfs/usr/local/bin`?

2017-04-05 19:39 UTC, vdice commented on Dockerfile
> +ARG VERSION=3.7
will do (technically it's the Jenkins [Remoting](https://github.com/jenkinsci/remoting) Module version; will update accordingly)

2017-04-05 21:21 UTC, bacongobbler commented
Once docs are added I'll LGTM this :)

2017-04-07 20:49 UTC, vdice commented
@bacongobbler docs added and chart updated!  PTAL

2017-04-07 21:14 UTC, krancour commented
I'm wondering if it doesn't make more sense to use `jenkinsci/jnlp-slave` as the base image. Wouldn't that spare us from having to include out own startup script?

2017-04-07 21:45 UTC, vdice commented
> I'm wondering if it doesn't make more sense to use jenkinsci/jnlp-slave as the base image

It would be preferable if we could.  However, the current Dockerfile as written does quite a few root-user tasks (apt-get install *, mkdir, chown, etc.) and the `jenkinsci/jnlp-slave` image has `USER jenkins` set.  If there is a way to reconfig our Dockerfile to be able to do all it needs to do but as the `jenkins` user, then I'd definitely be in favor.  (Also note some custom logic in the `jenkins-slave` script)

2017-04-08 00:39 UTC, bacongobbler commented
Is it possible to do this?

```
FROM jenkins/jnlp-slave
USER root
RUN apt-get install ...
USER jenkins
```

?

2017-04-08 00:40 UTC, bacongobbler commented
> (Also note some custom logic in the jenkins-slave script)

We can override the jenkins-slave script provided in jenkins/jnlp-slave. I had to do the same for deis/postgres and its docker-entrypoint script.

2017-04-08 00:41 UTC, bacongobbler commented
Either way we can refactor in the future. LGTM!

2017-04-08 00:41 UTC, bacongobbler approved these changes

2017-04-10 16:40 UTC, vdice commented
Great suggestions @krancour and @bacongobbler .  Pushed the latest changes and tested it via the following pipeline: https://ci.deis.io/job/builder-clone/1  

I'd like to get our k8s plugin pulling this image and running more jobs just to be sure before merging, but this does simplify things.

2017-04-10 16:55 UTC, vdice commented
Sigh; n/m... I was fooled by the pipeline b/c although the builder clone job using my agent succeeded, the downstream job was still using the previous jenkin-node:canary image.  Now when I flipped ci to use this test img, jobs fail w/ perms issues.  It seems we still need the container user to be root -- but would be great to refactor later.  I'll update this PR and keep testing...

2017-04-10 18:27 UTC, vdice commented
Ok, we're back to where this PR originally started.  In order to refactor the image to pull from `jenkinsci/jnlp-slave` and not use our custom `jenkins-slave` script, we'll need to make updates in the `deis/e2e-runner` project.  I'll file a ticket for this work.

2017-04-10 18:47 UTC, krancour approved these changes

2017-04-10 19:03 UTC, merged